### ISSUE TITLE
UI for import-map-overrides

### ISSUE THREAD

**Issue by joeldenning** [joeldenning/import-map-overrides#1]
Should we build a UI for import map overrides, such as the one shown in the following gif:

<img src="https://drive.google.com/uc?id=1cOpCP-Gfsn_sX9AuIft7UvbMHi5Z1KVm">

**Comment by dgreene1** [comment]
Sounds good to me! :)

**Comment by frehner** [comment]
The next release of single-spa-inspector will also support doing overrides when using this library, if that helps too :)
