### ISSUE TITLE
Safari design

### ISSUE THREAD

**Issue by BartJanvanAssen** [joeldenning/import-map-overrides#30]
Can we improve the design on the safari browser? its always fixed to the left bottom corner + transparent

<img width="829" alt="image" src="https://user-images.githubusercontent.com/4742816/85375845-2d88f300-b537-11ea-91f9-3985b42f14ad.png">

**Comment by joeldenning** [comment]
Sure. If you have time to submit a PR, that would be appreciated. Otherwise I may get to it in the next few weeks.
