### ISSUE TITLE
Question: Is it possible to always show the ui after a refresh?

### ISSUE THREAD

**Issue by cmacdonnacha** [joeldenning/import-map-overrides#46]
Right now after a refresh I have to click the button in the right bottom corner to view the UI. I was wondering if there was a way to keep this open even after a refresh?

Also, should we be using the `import-map-overrides` ui or the `single-spa-inspector` chrome extension or both?

**Comment by frehner** [comment]
>Also, should we be using the import-map-overrides ui or the single-spa-inspector chrome extension or both?

if you have import-map-overrides, then the chrome extension doesn't add much; no need to have both.

**Comment by cmacdonnacha** [comment]
Great thanks 👍
