### ISSUE TITLE
Confusing reload icon after adding an override

### ISSUE THREAD

**Issue by bradydowling** [joeldenning/import-map-overrides#57]
<img width="114" alt="Screen Shot 2021-06-22 at 9 38 50 AM" src="https://user-images.githubusercontent.com/6668371/122956602-2580b080-d34f-11eb-9e69-9126e6b01258.png">

This refresh icon is kinda confusing. It shows up only after you’ve changed an import map, which is also the exact time you’d want to refresh the page, which is generally what this icon means, but not here 😁

It _could_ be helpful to have an actual icon that reloads the page. But it would mainly be helpful to change this icon to something different (e.g. ⚙️) or just remove it entirely.

**Comment by joeldenning** [comment]
> This refresh icon is kinda confusing. It shows up only after you’ve changed an import map, which is also the exact time you’d want to refresh the page, which is generally what this icon means, but not here

It's unclear which situation you're talking about - are you referring to overrides automatically applied for libraries like `react` when using the `dev-libs` option (to use react.development.js instead of react.production.min.js)? If so, then the page does need a refresh for those overrides to be applied.

**Comment by bradydowling** [comment]
No. I'm talking about regular old import map overrides for an import map you've specified to localhost for example.

> the page does need a refresh for those overrides to be applied.

I fully understand that. And this is exactly what makes the UX confusing.

To reproduce:

1. Apply an override for an import map
2. The page refresh icon appears next to the `Inline Override` text but clicking it does not refresh the page, instead it opens the edit modal

**Comment by joeldenning** [comment]
I see, yeah I'm open to the reload icon becoming a button that reloads the page. Do you have interest in submitting a pull request implementing this?

**Comment by bradydowling** [comment]
Ya sure, I can look into it. I’ll let you know if I have a PR or if I just get too busy for it.

**Comment by bradydowling** [comment]
Sorry, just being realistic here, I won't be able to get to this in the near future so don't wait for me to implement this if you or anyone else finds time for this.

**Comment by joeldenning** [comment]
I had some time today so I implemented this in e00d6d99af2e216fcf7a154890bc263b6a883063 and released it in https://github.com/joeldenning/import-map-overrides/releases/tag/v2.4.0
