### ISSUE TITLE
Overrides triggers cross-origin issue when loaded into iframe (MS Teams)

### ISSUE THREAD

**Issue by pkarl** [joeldenning/import-map-overrides#61]
I believe this line: https://github.com/joeldenning/import-map-overrides/blob/5faf9e7a6226f5328252ca6f1645dc089d4d36d5/src/api/js-api.js#L114

is causing a cross-origin error when accessing our single-spa app when hosted inside of Microsoft Teams:

![Screen Shot 2022-01-10 at 11 08 48 AM](https://user-images.githubusercontent.com/8388/148799170-53c0430f-303b-4f86-ae7e-c6071bff2dd2.png)

If y'all confirm that this is behaving as expected, and that this appears to be the cause of this exception, then I'm happy to spin up a PR + tests. Just need a sign that I haven't got this completely mixed.

**Comment by joeldenning** [comment]
Resolved in #62 and released in https://github.com/joeldenning/import-map-overrides/releases/tag/v2.4.2
